export default function DadosDosFilmes() {
  const categorias = [
    {
      id: "1",
      titulo: "Em Alta",
      filmes: [
        {
          id: "1a",
          titulo: "Oppenheimer",
          subtitulo: "O mundo mudará para sempre",
          ano: "2023",
          duracao: "3h 00m",
          classificacao: "16+",
          nota: "8.9",
          genero: "Drama • Biografia • História",
          elenco: "Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.",
          cor: "#f2a27fff",
          imagem: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
          sinopse: "A história do físico americano J. Robert Oppenheimer, seu papel fundamental no Projeto Manhattan e o desenvolvimento da bomba atômica durante a Segunda Guerra Mundial."
        },
        {
          id: "1b",
          titulo: "Duna 2",
          subtitulo: "Vida longa aos guerreiros",
          ano: "2024",
          duracao: "2h 46m",
          classificacao: "14+",
          nota: "8.6",
          genero: "Ficção Científica • Aventura • Ação",
          elenco: "Timothée Chalamet, Zendaya, Rebecca Ferguson, Javier Bardem",
          cor: "#ff7b00ff",
          imagem: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
          sinopse: "Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família, diante de uma escolha entre o amor de sua vida e o destino do universo."
        },
        {
          id: "1c",
          titulo: "Barbie",
          subtitulo: "Ela pode ser tudo. Ele é só o Ken.",
          ano: "2023",
          duracao: "1h 54m",
          classificacao: "12+",
          nota: "7.0",
          genero: "Comédia • Fantasia • Aventura",
          elenco: "Margot Robbie, Ryan Gosling, America Ferrera, Will Ferrell",
          cor: "#ff00aaff",
          imagem: "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
          sinopse: "Depois de ser expulsa da Barbieland por não ser uma boneca perfeita, Barbie parte para o mundo humano acompanhada de Ken em busca da verdadeira felicidade e autodescoberta."
        },
        {
          id: "1d",
          titulo: "Poor Things",
          subtitulo: "Uma criatura fantástica",
          ano: "2023",
          duracao: "2h 21m",
          classificacao: "18+",
          nota: "7.9",
          genero: "Comédia • Drama • Romance • Ficção Científica",
          elenco: "Emma Stone, Mark Ruffalo, Willem Dafoe, Ramy Youssef",
          cor: "#533483",
          imagem: "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
          sinopse: "A incrível evolução de Bella Baxter, uma jovem trazida de volta à vida pelo brilhante e heterodoxo cientista Dr. Godwin Baxter, ansiosa para aprender e explorar o mundo ao seu redor."
        },
        {
          id: "1e",
          titulo: "Saltburn",
          subtitulo: "Um verão inesquecível",
          ano: "2023",
          duracao: "2h 11m",
          classificacao: "18+",
          nota: "7.1",
          genero: "Drama • Suspense • Comédia Ácida",
          elenco: "Barry Keoghan, Jacob Elordi, Rosamund Pike, Richard E. Grant",
          cor: "#2b2d42",
          imagem: "https://image.tmdb.org/t/p/w500/qjhahNLSZ70DYHp992sq1gwbYIR.jpg",
          sinopse: "Lutando para encontrar seu lugar na Universidade de Oxford, o estudante Oliver Quick é atraído para o mundo do charmoso e aristocrático Felix Catton, que o convida para passar um verão em Saltburn."
        },
      ],
    },
    {
      id: "2",
      titulo: "Ação",
      filmes: [
        {
          id: "2a",
          titulo: "John Wick 4",
          subtitulo: "Baba Yaga está de volta",
          ano: "2023",
          duracao: "2h 49m",
          classificacao: "16+",
          nota: "7.7",
          genero: "Ação • Suspense • Crime",
          elenco: "Keanu Reeves, Donnie Yen, Bill Skarsgård, Laurence Fishburne",
          cor: "#1b1b2f",
          imagem: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
          sinopse: "John Wick descobre um caminho para derrotar a Alta Cúpula. Mas antes que possa conquistar sua liberdade, Wick deve enfrentar um novo inimigo com poderosas alianças em todo o mundo."
        },
        {
          id: "2b",
          titulo: "Missão Impossível",
          subtitulo: "Acerto de Contas",
          ano: "2023",
          duracao: "2h 43m",
          classificacao: "14+",
          nota: "7.6",
          genero: "Ação • Aventura • Suspense",
          elenco: "Tom Cruise, Hayley Atwell, Ving Rhames, Simon Pegg",
          cor: "#162447",
          imagem: "https://image.tmdb.org/t/p/w500/NNxYkU70HPurnNCSiCjYAmacwm.jpg",
          sinopse: "Ethan Hunt e sua equipe do FMI embarcam em sua missão mais perigosa até agora: rastrear uma arma aterrorizante que ameaça toda a humanidade antes que caia em mãos erradas."
        },
        {
          id: "2c",
          titulo: "Top Gun",
          subtitulo: "Maverick",
          ano: "2022",
          duracao: "2h 10m",
          classificacao: "12+",
          nota: "8.3",
          genero: "Ação • Drama",
          elenco: "Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm",
          cor: "#1f4068",
          imagem: "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
          sinopse: "Depois de mais de trinta anos de serviço como um dos melhores aviadores da Marinha, Pete 'Maverick' Mitchell treina um destacamento de graduados para uma missão especializada."
        },
        {
          id: "2d",
          titulo: "Mad Max",
          subtitulo: "Estrada da Fúria",
          ano: "2015",
          duracao: "2h 00m",
          classificacao: "16+",
          nota: "8.1",
          genero: "Ação • Aventura • Ficção Científica",
          elenco: "Tom Hardy, Charlize Theron, Nicholas Hoult, Hugh Keays-Byrne",
          cor: "#1b262c",
          imagem: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
          sinopse: "Em um mundo pós-apocalíptico, Max se junta à Imperatriz Furiosa e a um bando de prisioneiras em fuga para escapar do tirano Immortan Joe através do deserto."
        },
      ],
    },
    {
      id: "3",
      titulo: "Comédia",
      filmes: [
        {
          id: "3a",
          titulo: "Superbad",
          subtitulo: "É Hoje",
          ano: "2007",
          duracao: "1h 53m",
          classificacao: "16+",
          nota: "7.6",
          genero: "Comédia",
          elenco: "Jonah Hill, Michael Cera, Christopher Mintz-Plasse, Bill Hader",
          cor: "#2d132c",
          imagem: "https://image.tmdb.org/t/p/w500/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg",
          sinopse: "Dois amigos adolescentes co-dependentes enfrentam a ansiedade da separação enquanto tentam comprar bebidas alcoólicas para uma festa do colégio e conquistar suas paixões."
        },
        {
          id: "3b",
          titulo: "The Grand Budapest",
          subtitulo: "O Grande Hotel Budapeste",
          ano: "2014",
          duracao: "1h 39m",
          classificacao: "14+",
          nota: "8.1",
          genero: "Comédia • Aventura • Drama",
          elenco: "Ralph Fiennes, F. Murray Abraham, Mathieu Amalric, Adrien Brody",
          cor: "#1c3334",
          imagem: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
          sinopse: "As aventuras de Gustave H, um lendário concierge de um famoso hotel europeu entre as guerras, e Zero Moustafa, o mensageiro que se torna seu amigo mais confiável."
        },
        {
          id: "3c",
          titulo: "Knives Out",
          subtitulo: "Entre Facas e Segredos",
          ano: "2019",
          duracao: "2h 10m",
          classificacao: "14+",
          nota: "7.9",
          genero: "Comédia • Mistério • Crime",
          elenco: "Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis",
          cor: "#2c003e",
          imagem: "https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
          sinopse: "O detetive Benoit Blanc investiga a misteriosa morte de um renomado escritor de romances policiais em sua mansão, onde todos os excêntricos familiares são suspeitos."
        },
      ],
    },
    {
      id: "4",
      titulo: "Documentários",
      filmes: [
        {
          id: "4a",
          titulo: "Free Solo",
          subtitulo: "Sem cordas, sem limites",
          ano: "2018",
          duracao: "1h 40m",
          classificacao: "10+",
          nota: "8.1",
          genero: "Documentário • Aventura • Esporte",
          elenco: "Alex Honnold, Tommy Caldwell, Jimmy Chin, Sanni McCandless",
          cor: "#0d0d0d",
          imagem: "https://image.tmdb.org/t/p/w500/v4QfYZMACODlWul9doN9RxE99ag.jpg",
          sinopse: "Acompanhe Alex Honnold enquanto ele tenta se tornar a primeira pessoa a escalar em estilo solo livre os 900 metros do paredão de granito El Capitan no Parque Nacional de Yosemite."
        },
        {
          id: "4b",
          titulo: "The Social Dilemma",
          subtitulo: "O Dilema das Redes",
          ano: "2020",
          duracao: "1h 34m",
          classificacao: "12+",
          nota: "7.6",
          genero: "Documentário • Drama",
          elenco: "Tristan Harris, Jeff Seibert, Bailey Richardson, Joe Toscano",
          cor: "#001011",
          imagem: "https://image.tmdb.org/t/p/w500/jcaM6V2tCtu6iMHDsGLBUbaYgYp.jpg",
          sinopse: "Especialistas em tecnologia e ativistas exploram o perigoso impacto humano e psicológico das redes sociais e como as plataformas digitais manipulam o comportamento dos usuários."
        },
        {
          id: "4c",
          titulo: "My Octopus Teacher",
          subtitulo: "Professor Polvo",
          ano: "2020",
          duracao: "1h 25m",
          classificacao: "Livre",
          nota: "8.1",
          genero: "Documentário",
          elenco: "Craig Foster, Tom Foster",
          cor: "#002b36",
          imagem: "https://image.tmdb.org/t/p/w500/hvTVZb7hBC8tZAGoEhH5eiMJu2B.jpg",
          sinopse: "Um cineasta forja uma amizade incomum com um polvo que vive em uma floresta de algas sul-africana, aprendendo lições valiosas sobre os mistérios e a fragilidade da vida."
        },
      ],
    },
    {
      id: "5",
      titulo: "Terror",
      filmes: [
        {
          id: "5a",
          titulo: "Hereditary",
          subtitulo: "Hereditário",
          ano: "2018",
          duracao: "2h 07m",
          classificacao: "16+",
          nota: "7.3",
          genero: "Terror • Mistério • Drama",
          elenco: "Toni Collette, Alex Wolff, Milly Shapiro, Gabriel Byrne",
          cor: "#200122",
          imagem: "https://image.tmdb.org/t/p/w500/4GFPuL14eXi66V96xBWY73Y9PfR.jpg",
          sinopse: "Após a morte da matriarca da família Graham, sua filha e netos começam a desvendar segredos crípticos e cada vez mais aterrorizantes sobre sua ancestralidade."
        },
        {
          id: "5b",
          titulo: "Midsommar",
          subtitulo: "O Mal Não Espera a Noite",
          ano: "2019",
          duracao: "2h 28m",
          classificacao: "18+",
          nota: "7.1",
          genero: "Terror • Drama • Mistério",
          elenco: "Florence Pugh, Jack Reynor, Vilhelm Blomgren, William Jackson Harper",
          cor: "#190a05",
          imagem: "https://image.tmdb.org/t/p/w500/7LEI8ulZzO5gy9Ww2NVCrKmHeDZ.jpg",
          sinopse: "Um casal viaja para a Suécia para visitar o lendário festival rural de solstício de verão de um amigo, mas o retiro idílico se transforma rapidamente em uma competição violenta e bizarra."
        },
        {
          id: "5c",
          titulo: "Get Out",
          subtitulo: "Corra!",
          ano: "2017",
          duracao: "1h 44m",
          classificacao: "14+",
          nota: "7.8",
          genero: "Terror • Suspense • Mistério",
          elenco: "Daniel Kaluuya, Allison Williams, Bradley Whitford, Catherine Keener",
          cor: "#0a0a0a",
          imagem: "https://image.tmdb.org/t/p/w500/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
          sinopse: "Um jovem afro-americano visita a propriedade da família de sua namorada branca durante o fim de semana, onde descobre um segredo sinistro por trás da recepção aparentemente acolhedora."
        },
      ],
    }
  ];

  return categorias;
}